### ISSUE TITLE
Please add Traefik

### ISSUE THREAD

**Issue by FAFDK** [GhostWriters/DockSTARTer#867] opened 2020-02-07 13:55 UTC
A wonderful addition would be **Traefik**
- https://hub.docker.com/_/traefik
- https://docs.traefik.io/
- https://docs.traefik.io/v2.0/getting-started/install-traefik/#use-the-official-docker-image

Additional info/tut:
- https://www.smarthomebeginner.com/traefik-reverse-proxy-tutorial-for-docker/
- https://www.smarthomebeginner.com/install-unifi-controller-on-docker/
- https://www.smarthomebeginner.com/google-oauth-with-traefik-docker/
- https://github.com/htpcBeginner/docker-traefik

To run Traefik as a Reverse-Proxy in front of Docker would be a nice choice. I know that there are different ways to setup things, but to get this working under DS's ecosys would be nice.

**Thx**

**Comment by nemchik** [comment] 2020-02-07 15:26
Duplicate of https://github.com/GhostWriters/DockSTARTer/issues/236 and https://github.com/GhostWriters/DockSTARTer/pull/272

Closing this as it's already been discussed and nothing has really changed with regards to how Traefik is setup.

**Closed by nemchik** 2020-02-07 15:27 UTC
