### ISSUE TITLE
Disabling/Removing

### ISSUE THREAD

**Issue by majo99** [GhostWriters/DockSTARTer#582] opened 2019-02-25 16:16 UTC
Hi at the risk of missing something obvious I am trying to remove sonarr but I can't find anything anywhere that tells me how to do so. As I said I have probably missed something somewhere and have searched for hours. It is just a case of  after following all instructions I can not get sonarr to read my directories my home folder so i have decided to uninstall the dockstarter version and revert back to the other one I was using. Amy help would be appreciated

**Comment by nemchik** [comment] 2019-02-25 17:32
First to answer your question about removing Sonarr:
If you run the DS menu and proceed through configuration > app selection you can unmark Sonarr from that menu and then complete the rest of the menus to the point where it asks you to run the containers and say yes. This will remove any de-selected containers. If Sonarr is the only container you enabled and did not change any other settings you will likely still be running Portainer and Ouroboros setup by DS. You can fully remove them by using the following commands:
```bash
ds -c down
ds -p
```
This will remove the containers as well as the images used by DS, but will leave any config files (user data) in place and Docker and other dependencies used by DS will still be installed. To remove the configs you can remove the ~/.docker folder.

---

To address Sonarr not being able to see your home folder:
This is actually by design. Apps run inside Docker containers are almost like running on a separate machine. Docker allows you to map volumes into the container from your host, and DockSTARTer allows you to configure how this happens fairly easily with defaults for each app that needs them. During the configuration menu of DS (full config) you are prompted to enter the locations for your downloads folder and media folders. After setting where these files are found on your host system the apps running inside of Docker containers will be able to see the folders mapped to other locations such as `/downloads` and `/movies`. There are a few benefits here but one of the main ones is if you ever need to change the actual location on your system of where those folders are you only need to change the variables in DS to point to the new locations and then restart your containers and they will all work without having to reconfigure each app. There are also security benefits and this makes moving to a new machine or performing clean installs of your OS quicker if you are copying your config from your previous installation.

If you need more information feel free to ask here or on our discord where there are plenty of people willing to help you get off the ground (and you likely won't have to wait for me to see it if I'm not available :smile: )

**Comment by majo99** [comment] 2019-02-25 17:39
Lol I am green as grass bud. I will try a totally fresh install

**Comment by majo99** [comment] 2019-02-25 21:17
Ok sadly I have followed the instructions and even changed permissions but eventually I gave in and just reinstalled using my old method and it worked like a charm.

**Comment by nemchik** [comment] 2019-02-25 21:58
Ok, no problem. Glad you've got something working. If you ever decide to give it another shot with DS feel free to ask if you need help. Like I mentioned above our Discord is a quicker way to get help than issues on GitHub.

**Closed by nemchik** 2019-02-25 21:58 UTC
