### ISSUE TITLE
[BUG] Install Broke Linux Mint

### ISSUE THREAD

**Issue by SolaFox** [GhostWriters/DockSTARTer#1718] opened 2024-01-15 21:53 UTC
I followed instructions for APT Systems. When I tried to reboot, it kept booting into emergency mode and nothing would load to attempt recovery, so I had to completely reinstall OS: Linux Mint 21 XFCE

**Comment by Mchar7** [comment] 2024-02-26 15:09
I cannot think of anything that DockSTARTer would do that could cause this, besides an apt upgrade or docker install command failing partway and rebooting without resolving the error.

I'm guessing you installed over the same disk and no longer have access to that system? With filesystem access, the cause could probably be found pretty easily. Otherwise, there is not enough info to know what happened here.

**Closed** 2024-06-12 00:08 UTC
Labels: bug, no-issue-activity
