### ISSUE TITLE
[Application Request]

### ISSUE THREAD

**Issue by cchalifo999** [GhostWriters/DockSTARTer#1500] opened 2022-07-25 21:31 UTC
# Name of the application airsonic-advanced insted of airsonic
The Linux server airsonic is  Deprecated 
## Docker Hub/GitHub Registry
lscr.io/linuxserver/airsonic

**Comment by dylanmtaylor** [comment] 2022-07-28 14:28
This is a duplicate of #1448

**Closed** 2022-07-28 14:29 UTC
Labels: enhancement, apps, docs
