### ISSUE TITLE
Alpine Linux support

### ISSUE THREAD

**Issue by MatusModder** [GhostWriters/DockSTARTer#1477] opened 2022-05-17 14:46 UTC
Hello. I have an idea. What about supporting Alpine Linux? It is a lightweight Linux distro meant for running Docker containers. And I know that many containers are built with Alpine, but Alpine is a great distro for servers when you switch it to the edge branch.

**Comment by nemchik** [comment] 2022-05-17 17:12
Closing as duplicate of https://github.com/GhostWriters/DockSTARTer/issues/663

**Closed by nemchik** 2022-05-17 17:12 UTC
