### ISSUE TITLE
NGINX Proxy Manager

### ISSUE THREAD

**Issue by jodfie** [GhostWriters/DockSTARTer#729] opened 2019-06-13 15:14 UTC
**Is your feature request related to a problem? Please describe.**
NGINX Proxy Manager is a great user friendly reverse proxy manager. 

**Describe the solution you'd like**
Integrate Jc21/Nginxproxymanager

**Additional context**
https://github.com/jc21/nginx-proxy-manager

**Comment by nemchik** [comment] 2019-08-31 22:37
Keep this.

I'm interested in this but haven't had time to look into it yet.

**Comment by Bockiii** [comment] 2019-09-22 10:59
Instead of using nginx, research traefik. It's the new and better way to do this and has a really good docker integration.

**Comment by nemchik** [comment] 2019-09-22 11:01
Better it's subjective.

Nginx has been around longer, has more features, is very well documented and has a large and active community of users.

**Comment by dutran88** [comment] 2019-10-05 02:32
Any updates with this?

**Comment by nemchik** [comment] 2019-10-05 02:43
It's not off the table, but I've been very busy with work and haven't had a chance to put it together. You're welcome to submit a PR to add it, or use overrides to run it personally until I've got time to look into it.

**Comment by kazo0** [comment] 2019-10-06 16:11
I'd like to have this very much. I can take a crack at implementing it if you don't mind.

**Comment by nemchik** [comment] 2019-10-06 16:12
Absolutely!

**Comment by kazo0** [comment] 2019-10-06 17:01
Sweet, you can assign it to me. I'll look into it this week/weekend!

**Comment by Bockiii** [comment] 2019-10-08 18:12
I not only take back my foolish words, but also added the proxy manager to dockstarter. I didn't test it (because I dont have a dev-environment right now), but it looks exactly like the additions of codeserver, monitorr and dasshio, so I assume it should work.

**Comment by Bockiii** [comment] 2019-10-08 18:34
Also, fyi @ op: I took the docker from jlesage, not jc21 because it includes the database and config, so its less setup.

**Comment by jodfie** [comment] 2019-10-09 04:04
**> Also, fyi @ op: I took the docker from jlesage, not jc21 because it includes the database and config, so its less setup.**
> 
> Only downside: no arm version.

i didn't know anyone else had created a version so cool!

**Closed** 2019-12-16 00:07 UTC
Labels: enhancement, good first issue, no-issue-activity

**Comment by andrewr78** [comment] 2020-04-29 15:23
I know this is a bit stale - but any further word on integrating this into dockstarter?

**Comment by nemchik** [comment] 2020-04-29 17:13
I looked into this just a few weeks ago. The issue is it requires you make a config file ahead of time and bind mount the file into the container. DS doesn't provide any container that requires this kind of setup. If we include a file bind mount in the DS templates and the file doesn't exist ahead of starting the container compose will create a folder (not a file) which just leads to confusion.

You can still run this via overrides.
